# Generated by Django 4.2.4 on 2023-08-31 20:15

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatanBoard',
            fields=[
                ('seed', models.IntegerField(max_length=22, primary_key=True, serialize=False)),
                ('resource_tiles_order', jsonfield.fields.JSONField()),
                ('probabilities_order', jsonfield.fields.JSONField()),
                ('pips_order', jsonfield.fields.JSONField()),
            ],
        ),
    ]
