# Generated by Django 4.2.4 on 2023-08-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_gen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catanboard',
            name='seed',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
